name: Build wheels
on: push
jobs:
  wheels-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: AMD64
            platform: x64
          - arch: x86
            platform: Win32
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.81.0/binaries/boost_1_81_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
    - name: Build QuantLib
      run: |
        Expand-Archive -Path QuantLib-1.29.zip -DestinationPath C:\local
        Copy-Item Build.props C:\local\QuantLib-1.29\
        Copy-Item Directory.Build.props C:\local\QuantLib-1.29\
        cd C:\local\QuantLib-1.29\
        msbuild QuantLib.vcxproj -p:Configuration="Release (static runtime)" -p:Platform=${{ matrix.platform }}
        dir lib
    - name: Unpack QuantLib-SWIG
      run: |
        Expand-Archive -Path QuantLib-SWIG-1.29.zip -DestinationPath .
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        QL_DIR: C:\local\QuantLib-1.29
        INCLUDE: C:\local\boost
        QL_STATIC_RUNTIME: 1
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-1.29/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-windows-${{ matrix.arch }}
        path: ./wheelhouse/*.whl